#include<stdio.h>


// |------------------------------|
// |           Stack              -> Function calls, local variables, return addresses.
// |------------------------------|
// |           Heap               -> Dynamically allocated memory (malloc, new).
// |------------------------------|
// |   Uninitialized Data (BSS)   -> Global/static variables initialized to 0 or left uninitialized.
// |------------------------------|
// |   Initialized Data (.data)   -> Global/static variables with non-zero initial values.
// |------------------------------|
// |     Read-Only Data (.rodata) -> String literals, const global/static data, jump tables.
// |------------------------------|
// |        Text Segment          -> Binary instructions generated by compiler (functions, loops, etc).
// |------------------------------|

int main(){

    // present in stack
    int x = 0;
    
    // goes in bss
    static int y = 0;

    // stored in .rodata, read only
    char *s = "Hello world";
    // s[0] = "M"; // not allowed, causing segmentation fault.
    // s is present in stack tho.

    printf("%s", s);
    y = 5;
    x = 1;

    // const only prevent modification, does not affet storage class
    // stays in stack
    const int z = 0;

    char msg[] = "Where will this be stored ?";
    // the string literal will be stored in .rodata segment, but the array is stored in stack.
    // the literal will be copied to array as .. 'w' 'h' .. .. '?' '\0'

    char *msg = "This is not modifiable !";
    // as literal is stored in .rodata, and msg is a pointer stored in stack.
    // It is pointing to Read only memory, therefore not modifiable.

    printf("%s", msg);

    printf("Exiting main ...\n");

    return 0;
}   